var BaseUrl = 'http://192.168.1.243/'

const endpoints = {

    login: "/login",
    verify: "/verify",
    basicInfo: "/basic-info",
    reserve: "/trip/reserve",
    tripMonit: "/trip/monit",
    tripFree: "/trip/free",
    trip: "/trip",
    tripDetails: "/trip/details",
    tripCopy: "/trip/copy",
    tripEdit: "/trip/edit",
    tripEditOrigin: "/trip/edit-origin",
    tripPriceDetails: "/trip/price-details",
    line: "/line",
    cities: "/cities",
    lineCheck: "/line/check",
    lineType: "/line/type",
    subscribers: "/subscribers",
    tripCancel: "/trip/cancel",
    uncancelTrip: "/trip/uncancel",
    tripCancelVoip: "/trip/cancel/by-voip",
    tripAssign: "/trip/assign",
    car: "/car",
    carBasicData: "/car/basic-data",
    complaintsType: "/complaint/type",
    carType: "/car/type",
    carClass: "/car/class",
    driver: "/driver",
    driverMCS: "/driver-mcs",
    driverCheck: "/driver/check",
    stationTurn: "/station/turn",
    stationDetails: "/station/details",
    stations: "/stations",
    stationsV2: "/stations/v2",
    accessibility: "/driver/accessibility",
    accessibilityHistory: "/driver/accessibility/history",
    stationCheck: "/station/check",
    stationCheckV2: "/station/check/v2",
    duplicateAddress: "/duplicate-address",

    channel: "/channel",
    ownerHistory: "/car/owner",
    reportTaximeter: "/report/taximeter",
    reportTripCount: "/report/trip-count",
    reportVerify: "/report/verify",
    reportTimeLine: "/report/time-line",
    retportTurnOverAtTime: "/report/turnover-at-time",
    reportDriverTripCount: "/report/driver/trip-count",
    rDriverRoute: "/report/driver/route",
    rDriverLocation: "/report/driver/location",
    reportStCountInQue: "/report/station/count-in-que",
    repotTripChartDaily: "/report/trip/daily/chart",
    repotTripChartMonthly: "/report/trip/monthly/chart",
    repotTripChartHourly: "/report/trip/hourly/chart",
    reportRFIDs: "/report/RFIDs",

    lock: "/driver/lock",
    return2turn: "/driver/return2turn",
    users: "/user",
    shift: "/shift",
    shiftGroup: "/shift/group",
    shiftGroupMember: "/shift/group/member",
    shiftPattern: "/shift/pattern",
    shiftRelease: "/shift/release",
    shiftPreview: "/shift/preview",
    shiftReport: "/shift/report",
    group: "/group",
    groupMember: "/group/member",
    settingDriver: "/setting/driver",
    settingOperator: "/setting/operator",
    settingTripManage: "/setting/trip-manage",
    settingTariffV2: "/setting/tariff/v2",
    settingTariff: "/setting/tariff",
    settingTariffParams: "/setting/tariff/params",
    settingTariffConditions: "/setting/tariff/conditions",
    settingAutoFreeTrip: "/setting/auto-free-trip",
    driverPayment: "/financial/driver-payment",
    payment2Driver: "/financial/payment2driver",
    financial: "/financial",
    driverBalance: "/driver/balance",
    news: "/news",
    weatherCondition: "/weather-condition",
    defMsg: "/def-msg",
    loc2add: "/map/loc2add",
    search: "/map/search",
    pointIOTurn: "/point-io/turn",
    pointIOBasic: "/point-io/basic",
    pointIORFID: "/point-io/RFID",
    pointIOTrip: "/point-io/trip",
    pointIOPrint: "/point-io/print",
    pointIODriver2St: "/point-io/driver2st",
    pointIOFrequentAddress: "/point-io/frequent-address",
    pointIOLast20Trip: "/point-io/last20trip",
    pointIOMobileVerify: "/point-io/verify",
    pointIOAuthentication: "/point-io/authentication",
    pointIOQueIO: "/report/point-io/que-io",
    pointIOTotalTripMonth: "/report/point-io/total-trip-month",
    pointIOTotalTripHour: "/report/point-io/total-trip-hour",
    messengerRoom: "/messenger/room",
    messengerChat: "/messenger/chat",
    directCallTo: "/trip/callto",
    surveyOptions: "/survey/options",
    physicalAction: "/physical-action",

    calcPrice: "/calc-price",
    company: "/company",
    carLineAuto: "/car/line/auto",
    carLineHistory: "/car-line/history",
    carDriversHistory: "/car-drivers/history",

    diskSpace: BaseUrl + 'disk-space',
    files: BaseUrl + 'files',
    backup: BaseUrl + 'backup',
    backupPercent: BaseUrl + 'backup/percent'
}
export default endpoints